# Generated by Django 5.1.6 on 2025-02-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('file_hash', models.CharField(max_length=64)),
                ('file_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('gpu_usage', models.FloatField(blank=True, null=True)),
                ('ram_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('kb_sent', models.FloatField()),
                ('kb_received', models.FloatField()),
            ],
        ),
    ]
