# Generated by Django 5.1.6 on 2025-02-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hw_id', models.CharField(max_length=50)),
                ('hw_type', models.CharField(max_length=100)),
                ('hw_description', models.TextField()),
                ('hw_status', models.CharField(max_length=20)),
            ],
        ),
    ]
